# Generated by Django 4.1.5 on 2023-01-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=30)),
                ('api_id', models.CharField(max_length=255)),
                ('api_hash', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
